global:
  imagePullPolicy: IfNotPresent

services:
  config-server:
    image: vantaicn/spring-petclinic-config-server
    port: 8888

  discovery-server:
    image: vantaicn/spring-petclinic-discovery-server
    port: 8761

  customers-service:
    image: vantaicn/spring-petclinic-customers-service
    port: 8081

  visits-service:
    image: vantaicn/spring-petclinic-visits-service
    port: 8082

  vets-service:
    image: vantaicn/spring-petclinic-vets-service
    port: 8083

  api-gateway:
    image: vantaicn/spring-petclinic-api-gateway
    port: 8080

  admin-server:
    image: vantaicn/spring-petclinic-admin-server
    port: 9090
